# Generated by Django 4.1.4 on 2023-01-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default='', upload_to='images/% Y/% m/% d/', verbose_name='изображение'),
        ),
    ]
