# Generated by Django 4.1.4 on 2023-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
